### ISSUE TITLE
Размер карточки

### ISSUE THREAD

**Issue by sashaalesin** [solid-happiness/stylish-cow#1]
Карточки становятся разного размера в зависимости от текста внутри:

![image](https://user-images.githubusercontent.com/22159301/111043082-b7744580-8451-11eb-8cf7-968e5e51aea8.png)

**Comment by sashaalesin** [comment]
Мб показывать 2-3 строчки описания, а остальные скрывать? У некоторых товаров оно очень длинное:

![image](https://user-images.githubusercontent.com/22159301/111043193-4b461180-8452-11eb-8f9d-a498334b31c2.png)

**Comment by dchebakov** [comment]
Сделал пока чтобы растягивались до одного размера в строке
